apiVersion: v1
kind: Service
metadata:
  name: python-ws-svc  # Name of the resource
spec:
  selector:
    app: pythonapp
  ports:
  - protocol: "TCP"
    port: 31000
    targetPort: 8081
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp                # Name of the Kubernetes resource
spec:
  selector:
    matchLabels:
      app: pythonapp
  replicas: 2
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: docker-python-app
        image: yp29/pythondeploy:pythonapp-latest
        ports:
        - containerPort: 8081